<div class="about-box">
<div class="about-title"><span>ORDERS  AND <span> TRACKING</span></span></div>
</div>

 <div class="fieldset">
    <h2 class="legend"><?php echo Mage::helper('sales')->__('Returns') ?></h2>

   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
       <ul class="form-list">
           <li style="clear:both;">
               <div class="input-box" style="float:left;width:150px;">
                   <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" style="width:300px;"/>
               </div>
           </li>
           <li style="clear:both;">
               <div class="input-box">
                   <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
                </div>
           </li>
           <li style="clear:both;">
               <div class="input-box" style="float:left;width:150px;">
                   <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;"/>
               </div>
           </li>
           <li style="clear:both;">
               <div class="input-box" style="float:left;width:150px;">
                   <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               </div>
           </li>
           <li id="oar-email" style="clear:both;">
               <div class="input-box" style="float:left;width:150px;">
                   <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  style="width:300px;"/>
               </div>
           </li>
           <li id="oar-zip" style="display:none;clear:both;">
               <div class="input-box" style="float:left;width:150px;">
                   <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" style="width:300px;"/>
               </div>
           </li>
           <li style="clear:both;">
		
               
           </li>
       </ul>
</div>
	    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('sales')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="Continue" class="button"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
		</div>
   </form>


<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
