<?php
/**
 * Mojo Crative & Technical Solutions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   GetSomeMojo
 * @package    GetSomeMojo_Pinterestmojo
 * @copyright  Copyright (c) 2012 Mitch Robles, Jr. (http://www.GetSomeMojo.net)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Mitch Robles, Jr. <info@GetSomeMojo.net>
 */
 	
	if($this->yeaH4yeaH): ?>
    
    
		<script type="text/javascript">
			(function() {
				window.PinIt = window.PinIt || { loaded:false };
				if (window.PinIt.loaded) return;
				window.PinIt.loaded = true;
				function async_load(){
					var s = document.createElement("script");
					s.type = "text/javascript";
					s.async = true;
					s.src = "http://assets.pinterest.com/js/pinit.js";
					var x = document.getElementsByTagName("script")[0];
					x.parentNode.insertBefore(s, x);
				}
				if (window.attachEvent)
					window.attachEvent("onload", async_load);
				else
					window.addEventListener("load", async_load, false);
			})();
        </script>


        <div id="mojoPinterest" align="<?=$this->pinAlign;?>" style="<?=$this->pinStyle;?>">
        	<a href="<?=$this->newUrl;?>" class="pin-it-button" count-layout="<?=$this->pinCount;?>">Pin It</a>
        </div>
        
<?php endif; ?>